title: I am Isaac
author: lssac7778
email: lssac7778@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is my home
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Isaac Han
  tagline: Developer, AI researcher
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/isaac_port.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  # generate social links in footer
  social_links:
    twitter: None
    github:  lssac7778
    linkedIn: None
    rss: rss
    dribbble: None
    flickr:   None
    instagram: lssac7778
    pinterest: jekyll
    youtube: None
    facebook: None
    soundcloud: None
    telegram: None
    gitlab: None

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
